name: Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use a specific Python version (e.g., 3.9, 3.10); '3.x' is a good general choice

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          cd docs
          make html  # This assumes you're using Sphinx with the standard Makefile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Path to your built HTML documentation
          # cname: yourcustomdomain.com  # Optional: If you have a custom domain