name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c constraints.txt -r requirements.txt  # Install everything BUT httpx
          pip install --no-deps httpx==0.25.2             # Install httpx *without* dependencies
          # Modify httpx metadata to require httpcore==0.17.3
          python -c "
            import pathlib, re
            p = pathlib.Path('/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/httpx-0.25.2.dist-info/METADATA')
            t = p.read_text()
            t = re.sub(r'httpcore==1.\*', 'httpcore==0.17.3', t)
            p.write_text(t)
            "

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html